import { writable } from 'svelte/store';

const statesOfAmerica = [
	{ name: 'Alabama', abbreviation: 'AL', emoji: '', enabled: 'false' },
	{ name: 'Alaska', abbreviation: 'AK', emoji: '', enabled: 'false' },
	{ name: 'Arizona', abbreviation: 'AZ', emoji: '', enabled: 'false' },
	{ name: 'Arkansas', abbreviation: 'AR', emoji: '', enabled: 'false' },
	{ name: 'California', abbreviation: 'CA', emoji: '', enabled: 'false' },
	{ name: 'Colorado', abbreviation: 'CO', emoji: '', enabled: 'false' },
	{ name: 'Connecticut', abbreviation: 'CT', emoji: '', enabled: 'false' },
	{ name: 'Delaware', abbreviation: 'DE', emoji: '', enabled: 'false' },
	{ name: 'Florida', abbreviation: 'FL', emoji: '', enabled: 'false' },
	{ name: 'Georgia', abbreviation: 'GA', emoji: '', enabled: 'false' },
	{ name: 'Hawaii', abbreviation: 'HI', emoji: '', enabled: 'false' },
	{ name: 'Idaho', abbreviation: 'ID', emoji: '', enabled: 'false' },
	{ name: 'Illinois', abbreviation: 'IL', emoji: '', enabled: 'false' },
	{ name: 'Indiana', abbreviation: 'IN', emoji: '', enabled: 'false' },
	{ name: 'Iowa', abbreviation: 'IA', emoji: '🌽', enabled: 'true' },
	{ name: 'Kansas', abbreviation: 'KS', emoji: '', enabled: 'false' },
	{ name: 'Kentucky', abbreviation: 'KY', emoji: '', enabled: 'false' },
	{ name: 'Louisiana', abbreviation: 'LA', emoji: '', enabled: 'false' },
	{ name: 'Maine', abbreviation: 'ME', emoji: '', enabled: 'false' },
	{ name: 'Maryland', abbreviation: 'MD', emoji: '', enabled: 'false' },
	{ name: 'Massachusetts', abbreviation: 'MA', emoji: '', enabled: 'false' },
	{ name: 'Michigan', abbreviation: 'MI', emoji: '', enabled: 'false' },
	{ name: 'Minnesota', abbreviation: 'MN', emoji: '❄️', enabled: 'true' },
	{ name: 'Mississippi', abbreviation: 'MS', emoji: '', enabled: 'false' },
	{ name: 'Missouri', abbreviation: 'MO', emoji: '', enabled: 'false' },
	{ name: 'Montana', abbreviation: 'MT', emoji: '', enabled: 'false' },
	{ name: 'Nebraska', abbreviation: 'NE', emoji: '', enabled: 'false' },
	{ name: 'Nevada', abbreviation: 'NV', emoji: '', enabled: 'false' },
	{ name: 'New Hampshire', abbreviation: 'NH', emoji: '', enabled: 'false' },
	{ name: 'New Jersey', abbreviation: 'NJ', emoji: '', enabled: 'false' },
	{ name: 'New Mexico', abbreviation: 'NM', emoji: '', enabled: 'false' },
	{ name: 'New York', abbreviation: 'NY', emoji: '', enabled: 'false' },
	{ name: 'North Carolina', abbreviation: 'NC', emoji: '', enabled: 'false' },
	{ name: 'North Dakota', abbreviation: 'ND', emoji: '', enabled: 'false' },
	{ name: 'Ohio', abbreviation: 'OH', emoji: '', enabled: 'false' },
	{ name: 'Oklahoma', abbreviation: 'OK', emoji: '', enabled: 'false' },
	{ name: 'Oregon', abbreviation: 'OR', emoji: '', enabled: 'false' },
	{ name: 'Pennsylvania', abbreviation: 'PA', emoji: '', enabled: 'false' },
	{ name: 'Rhode Island', abbreviation: 'RI', emoji: '', enabled: 'false' },
	{ name: 'South Carolina', abbreviation: 'SC', emoji: '', enabled: 'false' },
	{ name: 'South Dakota', abbreviation: 'SD', emoji: '', enabled: 'false' },
	{ name: 'Tennessee', abbreviation: 'TN', emoji: '', enabled: 'false' },
	{ name: 'Texas', abbreviation: 'TX', emoji: '', enabled: 'false' },
	{ name: 'Utah', abbreviation: 'UT', emoji: '', enabled: 'false' },
	{ name: 'Vermont', abbreviation: 'VT', emoji: '', enabled: 'false' },
	{ name: 'Virginia', abbreviation: 'VA', emoji: '', enabled: 'false' },
	{ name: 'Washington', abbreviation: 'WA', emoji: '', enabled: 'false' },
	{ name: 'West Virginia', abbreviation: 'WV', emoji: '', enabled: 'false' },
	{ name: 'Wisconsin', abbreviation: 'WI', emoji: '', enabled: 'false' },
	{ name: 'Wyoming', abbreviation: 'WY', emoji: '', enabled: 'false' }
];

export const statesOfAmericaInventory = writable(statesOfAmerica);
